### ISSUE TITLE
Unknown CMake command "LibChaos_Configure_Target"

### ISSUE THREAD

**Issue by JayChen1996** [ChaoticConundrum/h264-roi#5]
hello,I am compiling your code in linux, and I meet a cmake error shows in title. 
I use ```cmake ../h264-roi``` and it shows that:
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- LibChaos: Other (Static) - Core,Crypto,PNG,JPEG,WebP,SQlite3 - heads/master-0-gaa80e86
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen missing components:  dot
-- Could NOT find LATEX (missing: LATEX_COMPILER) 
CMake Error at CMakeLists.txt:37 (LibChaos_Configure_Target):
  Unknown CMake command "LibChaos_Configure_Target".

-- Configuring incomplete, errors occurred!
See also "/home/jaychen/GitCode/ROI_H264/h264-roi-build/CMakeFiles/CMakeOutput.log"

how can I solve the problem? thank you!

**Comment by naveenkumarmulabitmovin** [comment]
I have encountered the same problem. Could anyone suggest me to slove this

-- LibChaos: Other (Static) - Core,Crypto,PNG,JPEG,WebP,SQlite3 - heads/master-0-gaa80e86*
CMake Error at CMakeLists.txt:37 (LibChaos_Configure_Target):
  Unknown CMake command "LibChaos_Configure_Target".


-- Configuring incomplete, errors occurred!

**Comment by ChaoticConundrum** [comment]
Make sure the submodule is checked out. Do `git submodule update --init` in the repository.

**Comment by naveenkumarmulabitmovin** [comment]
It worked. thanks
